---
title: "cross_validation"
author: "Kaitlyn Wang"
date: "12/2/2021"
output: html_document
---

```{r}
library(tidyverse)
library(viridis)
library(modelr)
library(mgcv)
```

#Stimulate a dataset

```{r}
set.seed(1)

nonlin_df = 
  tibble(
    id = 1:100,
    x = runif(100, 0, 1),
    y = 1 - 10 * (x - .3) ^ 2 + rnorm(100, 0, .3)
  )

nonlin_df %>% 
  ggplot(aes(x = x, y = y)) +
  geom_point()
```

Create splits by hand; plot; fit models

```{r}
train_df = sample_n(nonlin_df, 80) %>% arrange(id)
test_df = anti_join(nonlin_df, train_df, by = "id")

ggplot(train_df, aes(x = x, y = y)) +
  geom_point() +
  geom_point(data = test_df, color = "red")
```

Fit my models:

```{r}
linear_mod = lm(y ~ x, data = train_df)
smooth_mod = mgcv::gam(y ~ s(x), data = train_df)
wiggly_mod = mgcv::gam(y ~ s(x, k = 30), sp = 10e-6, data = train_df)
```

Plot the result:

```{r}
train_df %>% 
  add_predictions(linear_mod) %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_point() +
  geom_line(aes(y = pred))
```

quantify the result:

```{r}
rmse(linear_mod, test_df)
rmse(smooth_mod, test_df)
rmse(wiggly_mod, test_df)
```

#cv iteratively

Use `modelr::crossv_mc`

```{r}
cv_df = 
  crossv_mc(nonlin_df, 100) %>% 
  mutate(
    train = map(train, as.tibble),
    test = map(test, as.tibble)
  )
```

Let's fit some models:

```{r}
cv_df = 
  cv_df %>% 
    mutate(
      linear_mod = map(.x = train, ~lm(y ~ x, data = .x)),
      smooth_mod = map(.x = train, ~gam(y ~ s(x), data = .x)),
      wiggly_mod = map(.x = train, ~gam(y ~ s(x, k = 30), sp = 10e-6, data = train_df))
    ) %>% 
    mutate(
      rmse_linear = map2_dbl(.x = linear_mod, .y = test, ~rmse(model = .x, data = .y)),
      rmse_smooth = map2_dbl(.x = smooth_mod, .y = test, ~rmse(model = .x, data = .y)),
      rmse_wiggly = map2_dbl(.x = wiggly_mod, .y = test, ~rmse(model = .x, data = .y))
    )
```

Look at output

```{r}
cv_df %>% 
  select(.id, starts_with("rmse")) %>% 
  pivot_longer(
    rmse_linear:rmse_wiggly,
    names_to = "model",
    values_to = "rmse",
    names_prefix = "rmse_"
  ) %>% 
  ggplot(aes(x = model, y = rmse)) +
  geom_boxplot()
```




